#!/usr/bin/env python3
"""Amalgamate the split irap_noroslib C++ headers + sources into the single header.

Source of truth:  cpp/dev/include/irap_noroslib/*.hpp  +  cpp/dev/src/*.cpp
Output:           cpp/include/irap_noroslib.hpp   (the file users copy)

  - Declarations are always visible.
  - Implementation is compiled only where IRAP_NOROSLIB_IMPLEMENTATION is defined
    (stb-style), so it lands in exactly one translation unit.
  - platform.hpp (the Winsock/POSIX compatibility layer) is emitted verbatim and
    FIRST, so its conditional <winsock2.h>/<sys/socket.h> includes stay inside
    their #if branches instead of being hoisted. The platform-specific system
    headers it owns are excluded from the global include hoist.

Run from anywhere:  python3 cpp/dev/tools/amalgamate.py
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEV = os.path.dirname(HERE)                        # cpp/dev
CPP = os.path.dirname(DEV)                          # cpp
INC = os.path.join(DEV, "include", "irap_noroslib")
SRC = os.path.join(DEV, "src")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(CPP, "include", "irap_noroslib.hpp")

# platform.hpp is handled specially (emitted verbatim, first); not in this list.
# Full filenames -- md5calc is a .h, the rest are .hpp. Order is dependency order.
HEADERS = ["message.hpp", "md5calc.h", "dynmsg.hpp",
           "std_msgs.hpp", "geometry_msgs.hpp", "sensor_msgs.hpp",
           "nav_msgs.hpp", "diagnostic_msgs.hpp", "trajectory_msgs.hpp",
           "actionlib_msgs.hpp", "std_srvs.hpp", "msgfile.hpp",
           "net_util.hpp", "xmlrpc.hpp", "tcpros.hpp",
           "udpros.hpp", "xmlrpc_client.hpp", "xmlrpc_server.hpp", "node.hpp",
           "dynamic_node.hpp", "actionlib.hpp", "dynamic_actionlib.hpp"]
SOURCES = ["net_util.cpp", "xmlrpc.cpp", "tcpros.cpp", "udpros.cpp",
           "xmlrpc_client.cpp", "xmlrpc_server.cpp", "node.cpp",
           "dynmsg.cpp", "msgfile.cpp"]

# System headers owned by platform.hpp (POSIX socket stack + Winsock). They must
# NOT be hoisted to the top unconditionally -- platform.hpp includes them behind
# the right #if branch.
PLATFORM_HEADERS = {
    "arpa/inet.h", "fcntl.h", "netdb.h", "netinet/in.h", "netinet/tcp.h",
    "sys/socket.h", "sys/time.h", "sys/select.h", "poll.h", "unistd.h",
    "winsock2.h", "ws2tcpip.h", "windows.h", "basetsd.h", "io.h",
    # the filesystem shims platform.hpp owns (the .msg file loader needs them)
    "dirent.h", "sys/stat.h", "sys/types.h",
}

SYS_INC = re.compile(r'^\s*#\s*include\s*<([^>]+)>')
IRAP_NOROSLIB_INC = re.compile(r'^\s*#\s*include\s*"irap_noroslib/')
PRAGMA = re.compile(r'^\s*#\s*pragma\s+once')


def split_file(path):
    """Return (portable_system_includes:set, body_without_includes_or_pragma)."""
    sys_inc, body = set(), []
    for line in open(path).read().splitlines():
        m = SYS_INC.match(line)
        if m:
            if m.group(1).strip().lower() not in PLATFORM_HEADERS:
                sys_inc.add(line.strip())
            # platform-owned headers are dropped here (platform.hpp provides them)
        elif IRAP_NOROSLIB_INC.match(line) or PRAGMA.match(line):
            continue
        else:
            body.append(line)
    return sys_inc, "\n".join(body).strip("\n")


def read_verbatim_no_pragma(path):
    return "\n".join(l for l in open(path).read().splitlines()
                     if not PRAGMA.match(l)).strip("\n")


def main():
    all_sys = set()
    hdr_bodies, src_bodies = [], []
    for h in HEADERS:
        s, b = split_file(os.path.join(INC, h))
        all_sys |= s
        hdr_bodies.append("// ===== irap_noroslib/%s =====\n%s" % (h, b))
    for c in SOURCES:
        s, b = split_file(os.path.join(SRC, c))
        all_sys |= s
        src_bodies.append("// ===== src/%s =====\n%s" % (c, b))

    platform = read_verbatim_no_pragma(os.path.join(INC, "platform.hpp"))

    banner = (
        "// irap_noroslib.hpp - single-header ROS pub/sub client (no ROS libraries).\n"
        "//\n"
        "// A real roscore and real ROS nodes treat irap_noroslib as a legitimate node: it\n"
        "// speaks the ROS wire protocols (XML-RPC master/slave + TCPROS/UDPROS)\n"
        "// directly. Topics, services, actions and parameters; std_msgs/geometry_msgs/\n"
        "// sensor_msgs built in, plus your own message structs.\n"
        "//\n"
        "// USAGE (header-only, stb-style):\n"
        "//   In ONE .cpp of your project:\n"
        "//       #define IRAP_NOROSLIB_IMPLEMENTATION\n"
        "//       #include \"irap_noroslib.hpp\"\n"
        "//   In every other file, just:\n"
        "//       #include \"irap_noroslib.hpp\"\n"
        "//   Compile with C++17 and link sockets/threads:\n"
        "//       Linux/macOS:  -std=c++17 -pthread\n"
        "//       Windows (MinGW): -std=c++17 -lws2_32   (MSVC auto-links ws2_32)\n"
        "//\n"
        "// Generated by dev/tools/amalgamate.py - do not edit by hand.\n"
        "#pragma once\n"
    )
    sys_block = "\n".join(sorted(all_sys))
    parts = [banner,
             "// ---- platform / socket compatibility (Winsock <-> POSIX) ----",
             platform,
             "// ---- portable standard-library includes ----",
             sys_block, "",
             "\n\n".join(hdr_bodies),
             "\n\n#ifdef IRAP_NOROSLIB_IMPLEMENTATION\n",
             "\n\n".join(src_bodies),
             "\n#endif // IRAP_NOROSLIB_IMPLEMENTATION"]
    open(OUT, "w").write("\n".join(parts) + "\n")
    print("wrote %s (%d lines)" % (OUT, len(open(OUT).read().splitlines())))


if __name__ == "__main__":
    main()
